# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrasee_core', '0002_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='protocol',
            field=models.CharField(choices=[('0', 'TCP'), ('1', 'UDP')], max_length=1),
        ),
    ]
