# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrasee_core', '0004_auto_20160221_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='environments',
            field=models.ManyToManyField(to='infrasee_core.Environment'),
        ),
        migrations.AddField(
            model_name='host',
            name='data_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrasee_core.DataCenter'),
        ),
    ]
