# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrasee_core', '0005_auto_20160222_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrasee_core.Environment'),
        ),
        migrations.AlterField(
            model_name='host',
            name='data_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrasee_core.DataCenter'),
        ),
    ]
