# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrasee_core', '0006_auto_20160222_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
