# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrasee_core', '0009_auto_20160222_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('ports', models.ManyToManyField(blank=True, to='infrasee_core.Port')),
            ],
        ),
    ]
