# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrasee_core', '0012_auto_20160228_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=64, verbose_name='IP address'),
            preserve_default=False,
        ),
    ]
